-- Carbon report tables. Idempotent. Does not alter emission_* schemas.

CREATE TABLE IF NOT EXISTS report_dept_subject (
  id                bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id           bigint(20)   NOT NULL,
  subject_node_id   bigint(20)   DEFAULT NULL,
  energy_allocation varchar(64)  NOT NULL,
  enabled           char(1)      NOT NULL DEFAULT '0',
  create_by         varchar(64)  DEFAULT '',
  create_time       datetime     DEFAULT NULL,
  update_by         varchar(64)  DEFAULT '',
  update_time       datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_report_dept_subject_dept (dept_id),
  KEY idx_report_dept_subject_alloc (energy_allocation)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报告部门与核算主体对照';

CREATE TABLE IF NOT EXISTS report_dept_profile (
  id                   bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id              bigint(20)   NOT NULL,
  legal_name           varchar(255) DEFAULT '',
  short_name           varchar(128) DEFAULT '',
  entity_code          varchar(64)  DEFAULT '',
  default_compiler     varchar(255) DEFAULT '',
  carbon_department    varchar(128) DEFAULT '',
  business_description text,
  company_overview     text,
  process_description  text,
  default_org_boundary text,
  default_accounting_method text,
  default_exclusion_note text,
  default_approver     varchar(64)  DEFAULT '',
  default_validator    varchar(64)  DEFAULT '',
  default_reviewer     varchar(64)  DEFAULT '',
  default_checker      varchar(64)  DEFAULT '',
  default_authors      varchar(255) DEFAULT '',
  header_template      varchar(512) DEFAULT '',
  version              int          NOT NULL DEFAULT 1,
  create_by            varchar(64)  DEFAULT '',
  create_time          datetime     DEFAULT NULL,
  update_by            varchar(64)  DEFAULT '',
  update_time          datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_report_dept_profile_dept (dept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报告企业档案';

CREATE TABLE IF NOT EXISTS report_task (
  id                       bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id                  bigint(20)   NOT NULL,
  title                    varchar(255) DEFAULT '',
  template_code            varchar(64)  DEFAULT 'suning',
  period_type              varchar(16)  NOT NULL DEFAULT 'YEAR',
  report_year              int          NOT NULL,
  report_month             int          DEFAULT NULL,
  period_start             date         DEFAULT NULL,
  period_end               date         DEFAULT NULL,
  subject_node_id          bigint(20)   DEFAULT NULL,
  emission_template_id     bigint(20)   DEFAULT NULL,
  calculation_template_id  bigint(20)   DEFAULT NULL,
  factor_template_id       bigint(20)   DEFAULT NULL,
  source_hash              varchar(64)  DEFAULT '',
  status                   varchar(32)  NOT NULL DEFAULT 'DRAFT',
  current_step             varchar(32)  DEFAULT 'basic',
  version                  int          NOT NULL DEFAULT 1,
  deleted_flag             char(1)      NOT NULL DEFAULT '0',
  metadata_json            json,
  entity_profile_json      json,
  organization_boundary_json json,
  emission_boundary_notes_json json,
  activity_prose_json      json,
  prior_year_json          json,
  chapter6_json            json,
  last_validation_json     json,
  create_by                varchar(64)  DEFAULT '',
  create_time              datetime     DEFAULT NULL,
  update_by                varchar(64)  DEFAULT '',
  update_time              datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_report_task_dept (dept_id),
  KEY idx_report_task_calc (dept_id, calculation_template_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='碳排放报告任务';

CREATE TABLE IF NOT EXISTS report_emission_source (
  id                bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id           bigint(20)   NOT NULL,
  report_id         bigint(20)   NOT NULL,
  category          varchar(128) DEFAULT '',
  facility          varchar(255) DEFAULT '',
  location          varchar(255) DEFAULT '',
  source            varchar(255) DEFAULT '',
  data_origin       varchar(16)  DEFAULT 'AUTO',
  source_table      varchar(64)  DEFAULT '',
  source_id         varchar(64)  DEFAULT '',
  source_value      varchar(64)  DEFAULT '',
  source_unit       varchar(32)  DEFAULT '',
  normalized_value  varchar(64)  DEFAULT '',
  normalized_unit   varchar(32)  DEFAULT '',
  source_hash       varchar(64)  DEFAULT '',
  override_reason   varchar(255) DEFAULT '',
  sort_order        int          DEFAULT 0,
  create_by         varchar(64)  DEFAULT '',
  create_time       datetime     DEFAULT NULL,
  update_by         varchar(64)  DEFAULT '',
  update_time       datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_report_emission_source_report (dept_id, report_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS report_activity_fuel (
  id                bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id           bigint(20)   NOT NULL,
  report_id         bigint(20)   NOT NULL,
  fuel_type         varchar(32)  NOT NULL,
  facility          varchar(255) DEFAULT '',
  quantity          decimal(18,6) DEFAULT 0,
  unit              varchar(32)  DEFAULT '',
  source_name       varchar(255) DEFAULT '',
  month             int          DEFAULT NULL,
  data_origin       varchar(16)  DEFAULT 'AUTO',
  source_table      varchar(64)  DEFAULT '',
  source_id         varchar(64)  DEFAULT '',
  source_value      decimal(18,6) DEFAULT NULL,
  source_unit       varchar(32)  DEFAULT '',
  normalized_value  decimal(18,6) DEFAULT NULL,
  normalized_unit   varchar(32)  DEFAULT '',
  source_hash       varchar(64)  DEFAULT '',
  override_reason   varchar(255) DEFAULT '',
  sort_order        int          DEFAULT 0,
  create_by         varchar(64)  DEFAULT '',
  create_time       datetime     DEFAULT NULL,
  update_by         varchar(64)  DEFAULT '',
  update_time       datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_report_activity_fuel_report (dept_id, report_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS report_activity_electricity (
  id                bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id           bigint(20)   NOT NULL,
  report_id         bigint(20)   NOT NULL,
  scope             varchar(64)  DEFAULT 'purchased-electricity',
  quantity_mwh      decimal(18,6) DEFAULT 0,
  source_name       varchar(255) DEFAULT '',
  month             int          DEFAULT NULL,
  data_origin       varchar(16)  DEFAULT 'AUTO',
  source_table      varchar(64)  DEFAULT '',
  source_id         varchar(64)  DEFAULT '',
  source_value      decimal(18,6) DEFAULT NULL,
  source_unit       varchar(32)  DEFAULT '',
  normalized_value  decimal(18,6) DEFAULT NULL,
  normalized_unit   varchar(32)  DEFAULT 'MWh',
  source_hash       varchar(64)  DEFAULT '',
  override_reason   varchar(255) DEFAULT '',
  sort_order        int          DEFAULT 0,
  create_by         varchar(64)  DEFAULT '',
  create_time       datetime     DEFAULT NULL,
  update_by         varchar(64)  DEFAULT '',
  update_time       datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_report_activity_elec_report (dept_id, report_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS report_activity_heat (
  id                bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id           bigint(20)   NOT NULL,
  report_id         bigint(20)   NOT NULL,
  site              varchar(255) DEFAULT '',
  quantity_gj       decimal(18,6) DEFAULT 0,
  source_name       varchar(255) DEFAULT '',
  month             int          DEFAULT NULL,
  heating_area_m2   decimal(18,6) DEFAULT NULL,
  heat_coefficient  decimal(18,6) DEFAULT NULL,
  data_origin       varchar(16)  DEFAULT 'AUTO',
  source_table      varchar(64)  DEFAULT '',
  source_id         varchar(64)  DEFAULT '',
  source_value      decimal(18,6) DEFAULT NULL,
  source_unit       varchar(32)  DEFAULT '',
  normalized_value  decimal(18,6) DEFAULT NULL,
  normalized_unit   varchar(32)  DEFAULT 'GJ',
  source_hash       varchar(64)  DEFAULT '',
  override_reason   varchar(255) DEFAULT '',
  sort_order        int          DEFAULT 0,
  create_by         varchar(64)  DEFAULT '',
  create_time       datetime     DEFAULT NULL,
  update_by         varchar(64)  DEFAULT '',
  update_time       datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_report_activity_heat_report (dept_id, report_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS report_workload (
  id                bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id           bigint(20)   NOT NULL,
  report_id         bigint(20)   NOT NULL,
  metric_name       varchar(128) DEFAULT '',
  quantity          decimal(18,6) DEFAULT 0,
  unit              varchar(32)  DEFAULT '',
  data_origin       varchar(16)  DEFAULT 'MANUAL',
  source_table      varchar(64)  DEFAULT '',
  source_id         varchar(64)  DEFAULT '',
  source_hash       varchar(64)  DEFAULT '',
  override_reason   varchar(255) DEFAULT '',
  sort_order        int          DEFAULT 0,
  create_by         varchar(64)  DEFAULT '',
  create_time       datetime     DEFAULT NULL,
  update_by         varchar(64)  DEFAULT '',
  update_time       datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_report_workload_report (dept_id, report_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS report_equipment (
  id                bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id           bigint(20)   NOT NULL,
  report_id         bigint(20)   NOT NULL,
  name              varchar(255) DEFAULT '',
  category          varchar(64)  DEFAULT '',
  quantity          decimal(18,4) DEFAULT 0,
  unit              varchar(32)  DEFAULT '',
  model             varchar(128) DEFAULT '',
  energy_type       varchar(64)  DEFAULT '',
  remark            varchar(255) DEFAULT '',
  data_origin       varchar(16)  DEFAULT 'MANUAL',
  source_id         varchar(64)  DEFAULT '',
  sort_order        int          DEFAULT 0,
  create_by         varchar(64)  DEFAULT '',
  create_time       datetime     DEFAULT NULL,
  update_by         varchar(64)  DEFAULT '',
  update_time       datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_report_equipment_report (dept_id, report_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS report_monitoring_device (
  id                bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id           bigint(20)   NOT NULL,
  report_id         bigint(20)   NOT NULL,
  name              varchar(255) DEFAULT '',
  model             varchar(128) DEFAULT '',
  accuracy          varchar(64)  DEFAULT '',
  location          varchar(255) DEFAULT '',
  calibration_frequency varchar(64) DEFAULT '',
  measurement_range varchar(64)  DEFAULT '',
  data_origin       varchar(16)  DEFAULT 'AUTO',
  source_table      varchar(64)  DEFAULT '',
  source_id         varchar(64)  DEFAULT '',
  sort_order        int          DEFAULT 0,
  create_by         varchar(64)  DEFAULT '',
  create_time       datetime     DEFAULT NULL,
  update_by         varchar(64)  DEFAULT '',
  update_time       datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_report_monitor_report (dept_id, report_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS report_file (
  id                bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id           bigint(20)   NOT NULL,
  report_id         bigint(20)   DEFAULT NULL,
  kind              varchar(16)  DEFAULT 'upload',
  role              varchar(64)  DEFAULT '',
  object_key        varchar(512) NOT NULL,
  original_name     varchar(255) DEFAULT '',
  mime_type         varchar(128) DEFAULT '',
  size_bytes        bigint(20)   DEFAULT 0,
  sha256            varchar(64)  DEFAULT '',
  snapshot_sha256   varchar(64)  DEFAULT '',
  create_by         varchar(64)  DEFAULT '',
  create_time       datetime     DEFAULT NULL,
  update_by         varchar(64)  DEFAULT '',
  update_time       datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_report_file_report (dept_id, report_id),
  KEY idx_report_file_snapshot (dept_id, snapshot_sha256, role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS report_import_batch (
  id                bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id           bigint(20)   NOT NULL,
  report_id         bigint(20)   NOT NULL,
  import_type       varchar(32)  DEFAULT '',
  status            varchar(32)  DEFAULT 'uploaded',
  file_id           bigint(20)   DEFAULT NULL,
  column_mapping    json,
  preview_rows      json,
  errors_json       json,
  create_by         varchar(64)  DEFAULT '',
  create_time       datetime     DEFAULT NULL,
  update_by         varchar(64)  DEFAULT '',
  update_time       datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_report_import_report (dept_id, report_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS report_generation_job (
  id                bigint(20)   NOT NULL AUTO_INCREMENT,
  dept_id           bigint(20)   NOT NULL,
  report_id         bigint(20)   NOT NULL,
  status            varchar(32)  NOT NULL DEFAULT 'queued',
  output_kind       varchar(16)  DEFAULT 'docx',
  progress          int          DEFAULT 0,
  locked_by         varchar(64)  DEFAULT '',
  heartbeat_at      datetime     DEFAULT NULL,
  attempt_count     int          DEFAULT 0,
  input_snapshot_json json,
  snapshot_sha256   varchar(64)  DEFAULT '',
  ai_enabled        char(1)      DEFAULT '0',
  docx_file_id      bigint(20)   DEFAULT NULL,
  pdf_file_id       bigint(20)   DEFAULT NULL,
  error_message     text,
  llm_call_count    int          DEFAULT 0,
  create_by         varchar(64)  DEFAULT '',
  create_time       datetime     DEFAULT NULL,
  update_by         varchar(64)  DEFAULT '',
  update_time       datetime     DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_report_job_report (dept_id, report_id),
  KEY idx_report_job_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
